import os

# Complete list from API
api_ships = [
    "00-3 Kraavan Medium Freighter",
    "431 Hauler Cargo Tug",
    "4R3 Light Assault Transport",
    "A-7 Hunter Interceptor",
    "A-Type Stiletto",
    "A/SF-01 B-wing Heavy Fast Attack Starfighter",
    "AA-9 Freighter-Liner",
    "Acclamator-class Planetary Assault Ship",
    "Action IV Bulk Freighter",
    "Action VI Bulk Transport",
    "Adz-class Destroyer",
    "Aggressor Assault Fighter",
    "Ainik-class Scientific Survey Vessel",
    "Alabak's Gold",
    "Alidade-class Long-Range Survey Ship",
    "Alpha-3 Nimbus-class V-wing Starfighter",
    "Alpha-class Xg-1 Star Wing Assault Gunboat",
    "Ancient Starfighter",
    "AO-2 Cometstrike-class Orbital Assault Pod",
    "ARC-170 Heavy Starfighter",
    "ARC-40b Scout-Reconnaissance Fighter",
    "Ark Angel",
    "Armos Modular Transport",
    "Arquitens-class Light Cruiser",
    "ARX-T3 Suncutter Light Interceptor",
    "Assault Frigate Mark II",
    "Assertor-class Command Dreadnought",
    "Aurore-class Freighter",
    "Auzituck-class Gunship",
    "B-7 Light Freighter",
    "Baleen-class Heavy Freighter",
    "Barloz-class Medium Freighter",
    "Barrage Gunship",
    "Baudo-class Star Yacht",
    "Belbullab-22 Heavy Starfighter",
    "Blade-32 Superiority Fighter",
    "Blockade Bandit",
    "Bloodblade",
    "Braha'tok-class Gunship",
    "Brute Corvette",
    "BTA-NR2 Y-wing",
    "BTL-A4 BTL-S3 Y-wing Attack Starfighter",
    "BTS-A2 H-Wing Long-Range Strike Starfighter",
    "C-9979 Landing Craft",
    "C-ROC Gozanti-class Light Cruiser",
    "Caisson-class Engineering Troop Carrier",
    "Cal Perquo",
    "Cantwell-class Arrestor Cruiser",
    "Carmine Bolt",
    "CEC Deep Space Recovery Vessel L-2783",
    "CEC HWK-1000 Light Freighter",
    "CEC WUD-500 Star Yacht",
    "CL-1c Lancet Interceptor",
    "Class A Modular Transport",
    "CloakShape Fighter",
    "Coneship",
    "Consular-class Light Cruiser",
    "CorelliSpace Gymsnor-3 Light Freighter",
    "CorelliSpace Gymsnor-4 Light Freighter",
    "CR25 Troop Carrier",
    "CR90 Corvette",
    "CR92a Assassin-class Corvette",
    "Crusader Corvette",
    "CSS-1 Corellian Star Shuttle",
    "Curich-class Shuttle",
    "Customized Firespray System Patrol Craft",
    "Cutlass-9 Patrol Fighter",
    "Cybershop Ship",
    "D-type Stealth Freighter",
    "Darkflare",
    "Darvro-class Light Freighter",
    "Defender-class Light Corvette",
    "Deliverance",
    "Delta-12 Skysprite",
    "Delta-6 System Defense Starfighter",
    "Delta-7 Aethersprite-class Interceptor",
    "Delta-class T-3c Shuttle",
    "Diamond-class Cruiser",
    "Dikutruni",
    "DP20 Gunship",
    "Dreadnought-class Heavy Cruiser",
    "Droch-class Boarding Ship",
    "Droid Tri-Fighter",
    "DS-1 Death Star",
    "DS-2 Death Star",
    "Dual Hemisphere-Omni Support Vessel",
    "E-7 E-Wing Multi-Role Starfighter",
    "EF-97 Intelligence Cruiser",
    "EF76 Nebulon-B Frigate",
    "End of Days",
    "Escape Pod",
    "Eta-2 Actis-class Light Interceptor",
    "Eta-class Shuttle",
    "Eta-class Supply Barge",
    "Executor-class Star Dreadnought",
    "Extended Range Z-95 Headhunter",
    "Far*Reach Reconnaissance Ship",
    "Fiery Mercy",
    "Firespray System Patrol Craft",
    "FireStar II-class Orbital Defense Station",
    "Flatline and Brilliance",
    "Fondor Haulcraft",
    "G-1A Heavy Starfighter",
    "G9 Rigger Light Freighter",
    "GAT-12H Skipray Blastboat",
    "Gaze Electric",
    "Ghost",
    "Ghtroc 720 Light Freighter",
    "Ginivex-class Fanblade Starfighter",
    "Gladiator-class Star Destroyer",
    "Golan I Space Defense Platform",
    "Gozanti-class Armed Transport",
    "GR-75 Medium Transport",
    "GS-100 Salvage Ship",
    "GX1 Short Hauler",
    "H-22A D-wing Heavy Attack Boat",
    "H-60 Tempest Heavy Bomber",
    "H-type Nubian Yacht",
    "Hammerhead Corvette",
    "Harbor-class Mobile Space Dock",
    "Hardcell-class Interstellar Transport",
    "Haven-class Mobile Space Dock",
    "HH-87 Starhopper Starfighter",
    "HLAF-500 Starfighter",
    "Hound's Tooth",
    "HT-2200 Medium Freighter",
    "HWK-290 Light Freighter",
    "Hyena-class Droid Bomber",
    "IE-440 Nighthawk Multi-Role Starfighter",
    "IG-2000",
    "IL-5 Ocula Modified Scouts",
    "ILH-KK Citadel-class Light Freighter",
    "Imperial Customs Corvette",
    "Imperial Customs Frigate",
    "Imperial II-class Star Destroyer",
    "Imperial I-class Star Destroyer",
    "Imperial System Patrol Craft",
    "Incom A-24 Sleuth-class Scout Ship",
    "Incom A-36 Pathfinder-class Force Reconnaissance Vessel",
    "Independence",
    "Indulgent-class Luxury Starliner",
    "Interdictor-class Heavy Cruiser",
    "IR-3F-class Light Frigate",
    "Iso-One",
    "Ithorian Herd Ship",
    "J-type Diplomatic Barge",
    "J-type Star Skiff",
    "Jadthu-class Landing Ship",
    "Jedi Sojourner",
    "Jedi Training Cruiser Crucible",
    "Jedi Vector",
    "JumpMaster 5000",
    "Kalevalan Star Yacht",
    "Kaminoan Observation Ship",
    "Kappa-class Shuttle",
    "Kazellis-class Light Freighter",
    "Keldabe-class Battleship",
    "Kihraxz Light Starfighter",
    "Koensayr AD-1S Modular Multi-Role Starfighter",
    "Kom'rk-class Gauntlet Fighter",
    "Krayt Fang",
    "KSE Rho-1 Limulus-class Courier",
    "KST-100 Kestrel Light Executive Transport",
    "LAF-250 Starfighter",
    "Lambda-class T-4a Long Range Shuttle",
    "Lancer-class Frigate",
    "Lancer-class Pursuit Craft",
    "Lando Calrissian's YT Dart",
    "Law & Order",
    "LH75 Specialty Live-Haul Freighter",
    "Life Boat",
    "Longbeam Cruiser",
    "Loronar E-9 Explorer-class Armed Long-Range Scout Vessel",
    "Lucrehulk-class Battleship",
    "Luxurious-class Yacht",
    "M12-L Kimogila Heavy Starfighter",
    "M3-A Scyk Interceptor",
    "Maelstrom-class Battle Cruiser",
    "MandalMotors M22-T Krayt Gunship",
    "Mandalorian Protectorate Fang Starfighter",
    "Mankvim-814 Light Interceptor",
    "Marauder-class Assault Corvette",
    "Max-7 Rono Freighter",
    "MC-18 Light Freighter",
    "MC30c Frigate",
    "MC40a Light Cruiser",
    "MC75 Star Cruiser",
    "MC80 Liberty Type Heavy Star Cruiser",
    "MC80a Home One Type Heavy Star Cruiser",
    "MG-100 StarFortress SF-17",
    "Millennium Falcon",
    "Minstrel-class Space Yacht",
    "Mist Hunter",
    "Miy'til Starfighter",
    "Mk IX Orbital Maintenance Depot",
    "Mobile Tac-Pod",
    "Mobquet Medium Transport",
    "Modified CloakShape Starfighter",
    "Modified TIE Bomber",
    "MPO-1400 Purgill-class Star Cruiser",
    "Munificent-class Command, Control, and Communications Frigate",
    "Munificent-class Heavy Frigate",
    "N-1 Starfighter",
    "N.R. Correctional Transport",
    "Nantex-class Territorial Defense Starfighter",
    "ND-47 Stalwart Bulk Freighter",
    "Nightflyer",
    "Nihil Strikeship",
    "Nu-class Transport",
    "Omicron-class Attack Shuttle",
    "Onager-class Star Destroyer",
    "Outland TIE Fighter",
    "Pacifier Cruiser",
    "Pathfinder Scout Ship",
    "PB-950 Patrol Boat",
    "Pelta-class Frigate",
    "Penumbra Stealth Freighter",
    "Phantom",
    "Phantom II",
    "Phoenix Home",
    "Porax-38 Starfighter",
    "Porax-48 Gunship",
    "PPB Pocket Patrol Boat",
    "Praetor II-class Star Battlecruiser",
    "Preybird-class Starfighter",
    "Prototype-B6",
    "Providence-class Dreadnought",
    "Punishing One",
    "Punworcca 116-class Interstellar Sloop",
    "Q-Signal Messenger Drone",
    "Quasar Fire-class Escort Carrier",
    "R-41 Starchaser",
    "R-60 T-wing Interceptor",
    "Raider II-class Corvette",
    "Raider-class Corvette",
    "Razor Crest",
    "Regulator-class Patrol Vessel",
    "Neutron Star-class Bulk Cruiser",
    "Renegade's Blood",
    "Republic Z-95 Headhunter",
    "Rogue-class Starfighter",
    "RZ-1 A-wing Light Interceptor",
    "RZ-2 A-wing",
    "S-type Racing Sloop",
    "Sabine's TIE Fighter",
    "Savrip",
    "Scavenger Tug",
    "Scurrg H-6 Bomber",
    "Secutor-class Battlecarrier",
    "Sentinel-class Landing Craft",
    "Sentry Droid",
    "Shadow Caster",
    "Shadow Raptor",
    "Sheathipede-class Shuttle",
    "Shell-Cracker Prototype",
    "Shen's Yacht The Venture",
    "Shuttle Pod",
    "Sienar Fleet Systems Legate-class Courier",
    "Simiyiar Light Freighter",
    "Slave I",
    "Solemn Star",
    "SoroSuub Luxury 3000 Space Yacht",
    "Space Master Medium Transport",
    "SS-54 Light Assault Gunship",
    "Star Galleon Armed Transport",
    "Starbolt Assault Carrier",
    "Starhawk-class Battleship",
    "Starlight-class Light Freighter",
    "StarViper M-2",
    "StarViper-class Attack Platform",
    "Starwind Pleasure Yacht",
    "Strike Cruiser",
    "Subjugator-class Heavy Cruiser",
    "Surronian Conqueror-class Assault Ship",
    "Surveyor-class Reconnaissance Frigate",
    "Suwantek TL-1200 Transport",
    "Syliure-25 Hyperdrive Sled",
    "T-6 Shuttle",
    "T-65B X-wing Multi-role Starfighter",
    "T-70 X-wing",
    "T-85 X-wing",
    "Tallanx-class Stealth Fighter",
    "Tallon's Modified Z-95s",
    "Tam Blackstar's TIE Hunter",
    "Temple-class Heavy Freighter",
    "The Beacon",
    "The Booster BX",
    "The Broken Horn",
    "The Deep Dark",
    "The Diligent",
    "The Eternal Wrath",
    "The Fereallis",
    "The Icarii-7",
    "The Lucky Guess",
    "The Night Buzzard",
    "Theta-class T-2c Shuttle",
    "Thweek's Custom G1-M4-C Dunelizard",
    "TIE Advanced v1",
    "TIE Advanced x1",
    "TIE Auto-fighter",
    "TIE Bomber (First Order)",
    "TIEag Aggressor Starfighter",
    "TIEca Punisher Starfighter",
    "TIEd Defender Multi-role Starfighter",
    "TIEfo",
    "TIEhu Hunter Multi-role Starfighter",
    "TIEin Interceptor",
    "TIEln Starfighter",
    "TIEmg Mining Guild Starfighter",
    "TIEph Phantom Multi-role Stealth Starfighter",
    "TIErb Brute Heavy Starfighter",
    "TIErp Reaper Assault Transport",
    "TIEsa Tactical Bomber",
    "TIEsf",
    "TIEsk Striker Multi-role Fighter",
    "TIEvn Silencer",
    "Tireless Wanderer",
    "TL-18b Medium Transport",
    "Ton-Falk-class Escort Carrier",
    "Traffic Interdiction Vessel",
    "Trandoshan Dropship",
    "Trident-class Assault Ship",
    "Ubrikkian Industries Kossak-class Frigate",
    "Ubrikkian Industries Seltiss-2 Caravel",
    "Upsilon-class Command Shuttle",
    "UT-60D U-wing Troop Transport",
    "V-19 Torrent",
    "V-19b Dart Personal Flyer",
    "VCX-100 Light Freighter",
    "VCX-series Auxiliary Starfighter",
    "Venator-class Star Destroyer",
    "Victory II-class Star Destroyer",
    "Victory-class Star Destroyer",
    "Vigil-class Corvette",
    "Vindicator-class Heavy Cruiser",
    "VT-49 Decimator",
    "Vulture-class Droid Starfighter",
    "Wander-class Jump Freighter",
    "Wayfarer-class Medium Freighter",
    "Wheel Security Starfighters",
    "World's End Station",
    "WTK-85A Interstellar Transport",
    "Xanter-class Deep-Space Exploration Frigate",
    "Xi-class Light Shuttle",
    "Xiytiar-class Heavy Transport",
    "Y164 Slave Transport",
    "YC-123B Transport Hauler",
    "YG-4210 Light Freighter",
    "YG-4400 Light Freighter",
    "YKL-37R Nova Courier",
    "Yorik-vec Scout Cruiser",
    "YQ-400 Monitor-Class System Patrol Ship",
    "YT Dart",
    "YT-1000 Light Freighter",
    "YT-1200 Light Freighter",
    "YT-1210 Light Freighter",
    "YT-1300 Light Freighter",
    "YT-1760 Small Transport",
    "YT-2000 Light Freighter",
    "YT-2400 Light Freighter",
    "YV-560 Light Freighter",
    "YV-666 Light Freighter",
    "YV-929 Light Freighter",
    "YZ-775 Medium Transport",
    "Z-28 Skywing",
    "Z-95-AF4 Headhunter",
    "Z-95-AF4-H Heavy-95 Multi-Role Starfighter",
    "Z-TIE",
    "Zenuas 33 Starfighter",
    "Zeta-class Heavy Cargo Shuttle",
    "ZH-25 Questor Light Freighter",
]

# Get existing files
starship_dir = r"E:\Users\Mederic\Documents\Projet\Star Wars FFG\Lore\Vehicles\Starship"
capital_dir = r"E:\Users\Mederic\Documents\Projet\Star Wars FFG\Lore\Vehicles\Capital Ship"

existing_files = set()
for d in [starship_dir, capital_dir]:
    if os.path.exists(d):
        for f in os.listdir(d):
            if f.endswith('.md'):
                name = f[:-3]  # Remove .md
                existing_files.add(name)

# Find missing
missing = []
for ship in api_ships:
    found = False
    for existing in existing_files:
        if ship.lower() == existing.lower() or ship.lower().replace("'", "").replace('"', '').replace("*", "") in existing.lower() or existing.lower() in ship.lower():
            found = True
            break
    if not found:
        missing.append(ship)

print(f"Total API ships: {len(api_ships)}")
print(f"Total existing files: {len(existing_files)}")
print(f"\nMissing ships ({len(missing)}):")
for m in sorted(missing):
    print(f"  - {m}")
